var config = {
  serverUrl: "https://scoreboard-receiver.toki.id/serve",
  refreshIntervalInMs: 5000,
  contestStartTimestampInMs: 1724907900000,
  contestDurationInMs: 3600000,
  contestants: {
    JIDUSERPohDWfJgme2lEKoZj3OR: {
      username: "24049101000108u",
      name: "Muhammad Abdullah Azzam",
      school: "Sekolah Indonesia Singapura Tingkat SMA",
      province: "Luar Negeri",
    },
    JIDUSERGoD8TutINJ5wfm0HbBhs: {
      username: "24040606001418u",
      name: "Nurul Fajrina",
      school: "SMAN Modal Bangsa Aceh",
      province: "Aceh",
    },
    JIDUSERvozUkxgStv8yu7jFvSZo: {
      username: "24042206000119u",
      name: "Putu Rizki Manik Widiadnyana",
      school: "SMAN 1 Singaraja",
      province: "Bali",
    },
    JIDUSERbZXGGzW4eDYlQIUggqL8: {
      username: "24042208000118u",
      name: "I Gede Made Adi Putra Adnyana",
      school: "SMAN 1 Tabanan",
      province: "Bali",
    },
    JIDUSERlBMNBD61ZxhvnnniERSx: {
      username: "24042201000718u",
      name: "I Ketut Anand Amertha",
      school: "SMAN 3 Denpasar",
      province: "Bali",
    },
    JIDUSERDDWltwwDGy12RO9kMhe1: {
      username: "24042201001119u",
      name: "Jonathan Sebastian Sindhu",
      school: "SMAN 4 Denpasar",
      province: "Bali",
    },
    JIDUSERe4cwQUHbatGSvrFVa6mI: {
      username: "24043008000917u",
      name: "Jeremy Gerald Sutanto",
      school: "SMAK BPK PENABUR Gading Serpong",
      province: "Banten",
    },
    JIDUSERacZ8pvAug2BdO23zQx5A: {
      username: "24043008017418u",
      name: "Lionel Untung Wijaya",
      school: "SMA Pahoa",
      province: "Banten",
    },
    JIDUSERdadfPp4W6g5BZavniGti: {
      username: "24043008000920u",
      name: "Nathaniel Farrell Irawan",
      school: "SMAK BPK PENABUR Gading Serpong",
      province: "Banten",
    },
    JIDUSERpkZKRq8HadUGBceLLBLB: {
      username: "24043008016009u",
      name: "Rupert Hokada",
      school: "SMA UPH College",
      province: "Banten",
    },
    JIDUSERsy6RiRwpux6R7hCD30OF: {
      username: "24043004017417u",
      name: "Hayyan Ahmad Al Ghifary",
      school: "MAN Insan Cendekia Serpong",
      province: "Banten",
    },
    JIDUSERRaaTV8KAYJHo9ILMYKKF: {
      username: "24042601010218u",
      name: "Nora Indah Fransiska",
      school: "MAN 2 Kota Bengkulu",
      province: "Bengkulu",
    },
    JIDUSEROEKRXAd3g4ZP4zhgZqDQ: {
      username: "24040402005610u",
      name: "Bagas Anggareksa Irsyad Dhanisywara",
      school: "SMA Kesatuan Bangsa Bantul",
      province: "D. I. Yogyakarta",
    },
    JIDUSERfYhFW8km1W3TkvIc1Bwy: {
      username: "24040402014803p",
      name: "Danendra Naufal Sinambela",
      school: "SMP Kesatuan Bangsa Bantul",
      province: "D. I. Yogyakarta",
    },
    JIDUSERyeG4qxEPprKnPwQmGNI6: {
      username: "24040402014804p",
      name: "Leonardus Lintang Panji Utama",
      school: "SMP Kesatuan Bangsa Bantul",
      province: "D. I. Yogyakarta",
    },
    JIDUSERU0q0GtcxuiVP3fMEU2v4: {
      username: "24040401000118u",
      name: "Maximus Quinn Hertada",
      school: "SMAN 3 Yogyakarta",
      province: "D. I. Yogyakarta",
    },
    JIDUSERep5SAM2QpRDbnxbyEADJ: {
      username: "24040401001517u",
      name: "Mohammad Aryasatya Arifien",
      school: "SMAN 1 Yogyakarta",
      province: "D. I. Yogyakarta",
    },
    JIDUSERubhSti5M0mE1MDkLpD8v: {
      username: "24040103000816u",
      name: "Darryl Nathanael",
      school: "SMAK 1 BPK PENABUR Jakarta",
      province: "DKI Jakarta",
    },
    JIDUSER16zfcMONgW81W7hToc2u: {
      username: "24040103001918u",
      name: "Lionel Marco Wijaya",
      school: "SMAN 19 Jakarta",
      province: "DKI Jakarta",
    },
    JIDUSERsycvrXQStXc68AbQqEvL: {
      username: "24040103021815u",
      name: "Mitchell Joshua Hong",
      school: "SMA Citra Kasih",
      province: "DKI Jakarta",
    },
    JIDUSERnLb7KGf4lBKH0l1kW6hI: {
      username: "24040103100720u",
      name: "Stanislaus Harglen Utama Sitompul",
      school: "SMA Wardaya",
      province: "DKI Jakarta",
    },
    JIDUSERASotzomNYaOFPAoiIzSo: {
      username: "24040101006019u",
      name: "Moshes Yosepa Manihuruk",
      school: "SMA Kanisius Jakarta",
      province: "DKI Jakarta",
    },
    JIDUSERyjN3HXzCQybC7mzgGSbz: {
      username: "24040101006020u",
      name: "Rainer Evan Rusly",
      school: "SMA Kanisius Jakarta",
      province: "DKI Jakarta",
    },
    JIDUSERZXJ4rseQ1KWghpgfMzgb: {
      username: "24040101004314u",
      name: "Vincent Armando",
      school: "SMAK 2 BPK PENABUR Jakarta",
      province: "DKI Jakarta",
    },
    JIDUSER9cMN4HB2lMwnBvshDz4Q: {
      username: "24040105014714u",
      name: "Christopher Widyadi",
      school: "SMA ACS Jakarta",
      province: "DKI Jakarta",
    },
    JIDUSERJLlaiKj78zm7nC6PzvJb: {
      username: "24040105015518u",
      name: "Felipe Nathanael Corinthians Sitorus",
      school: "SMAN Unggulan M. H. Thamrin",
      province: "DKI Jakarta",
    },
    JIDUSERZY5Por2QT2Af8vOxtsdD: {
      username: "24040102024102u",
      name: "Devlin Mikha Dharmawan",
      school: "SMA Beacon Academy",
      province: "DKI Jakarta",
    },
    JIDUSERfxQakJ4RyJgHx9ayX9aj: {
      username: "24042905000718u",
      name: "Tibyan Kalam Haq",
      school: "MAN Insan Cendekia Gorontalo",
      province: "Gorontalo",
    },
    JIDUSERotUdpa7HnQBsm0DZ9ruL: {
      username: "24041001001217u",
      name: "Kevin Sie",
      school: "SMA Xaverius 1 Jambi",
      province: "Jambi",
    },
    JIDUSERtBMUZ55AFMamWINevEFU: {
      username: "24040212000717u",
      name: "Glenn Matthew Sebastian",
      school: "SMAN 1 Cikarang Pusat",
      province: "Jawa Barat",
    },
    JIDUSERREX2DJrg9ELETbLFA7No: {
      username: "24040213010901u",
      name: "Owen Sidarta",
      school: "SMA Pelita Harapan Sentul",
      province: "Jawa Barat",
    },
    JIDUSERhPOfRM6maYuBsQxpeSat: {
      username: "24040201008216u",
      name: "Flavio Harigunawan Tetjiakusuma",
      school: "SMA Santa Maria 1 Bandung",
      province: "Jawa Barat",
    },
    JIDUSERF0Jar644aLe3QmYL0bKW: {
      username: "24040203000417u",
      name: "Muhammad Nanda Alfarizi",
      school: "SMAN 4 Bekasi",
      province: "Jawa Barat",
    },
    JIDUSERQgI1dJ8F3wLbMQY566da: {
      username: "24040203006419u",
      name: "Naufal Aulia Wicaksono",
      school: "SMA Islam Al-Azhar 4 Bekasi",
      province: "Jawa Barat",
    },
    JIDUSERbdjTDUrIzC3HqE4H7QPQ: {
      username: "24040206000216u",
      name: "Adrian Nathanael Setiawan",
      school: "SMAN 2 Cirebon",
      province: "Jawa Barat",
    },
    JIDUSERVVjR94ye0nnWckS9PoF5: {
      username: "24040206001809u",
      name: "Clement Kevin Tanadi",
      school: "SMA Santa Maria 1 Cirebon",
      province: "Jawa Barat",
    },
    JIDUSERC7PKp8q81Pnn8J12x7la: {
      username: "24040206000220u",
      name: "Victoriano Iman Santosa",
      school: "SMAN 2 Cirebon",
      province: "Jawa Barat",
    },
    JIDUSERIhb2mjpBmi6la8fMscW4: {
      username: "24040207011004p",
      name: "Luvidi Pranawa Alghari",
      school: "SMP Pribadi Depok",
      province: "Jawa Barat",
    },
    JIDUSERRQ6SoNgGYszeQvx81hnm: {
      username: "24040207003712u",
      name: "Rakha Aziztama Adinindya",
      school: "SMA Pribadi Depok",
      province: "Jawa Barat",
    },
    JIDUSEReHGf9WbGQYfmPdWPjwWc: {
      username: "24040307021914u",
      name: "Amiri Danish Kazi",
      school: "SMA Al-Irsyad Purwokerto",
      province: "Jawa Tengah",
    },
    JIDUSER5lVJ1DSPpemnMh1XN5BU: {
      username: "24040307021915u",
      name: "Azzam Harzuqi",
      school: "SMA Al-Irsyad Purwokerto",
      province: "Jawa Tengah",
    },
    JIDUSEREhqavhPaoZjrAKjN1oS1: {
      username: "24040307000216u",
      name: "Bimo Ataullah Rahman",
      school: "SMAN 1 Banyumas",
      province: "Jawa Tengah",
    },
    JIDUSERJNTVdjZqnSJYlDvdA7ie: {
      username: "24040316100316u",
      name: "Claire Shane Ailie Sumantri",
      school: "SMA Pradita Dirgantara Boyolali",
      province: "Jawa Tengah",
    },
    JIDUSERn4FQqAqrwHKh6jOLGR0S: {
      username: "24040316100319u",
      name: "M. Fatih Danika",
      school: "SMA Pradita Dirgantara Boyolali",
      province: "Jawa Tengah",
    },
    JIDUSERKxpetebzCcJNjBKkALuV: {
      username: "24040312022116u",
      name: "Laksamana Gusti Athur Antoni",
      school: "SMA Taruna Nusantara Magelang",
      province: "Jawa Tengah",
    },
    JIDUSERRqrXsCDM6HVfYeJ9JjNp: {
      username: "24040330001118u",
      name: "Ilham Ligar Samudra",
      school: "SMAN 2 Ungaran",
      province: "Jawa Tengah",
    },
    JIDUSERiL7fwSlriat0chlhq2iY: {
      username: "24040304050217u",
      name: "Kaysan Navid Musyaffa",
      school: "MAN Insan Cendekia Pekalongan",
      province: "Jawa Tengah",
    },
    JIDUSERi8UAacgbzJGUsB7qDajs: {
      username: "24040301024415u",
      name: "Radistha Kriska Dahana Purusa",
      school: "SMA Semesta BBS Semarang",
      province: "Jawa Tengah",
    },
    JIDUSER1QsarsUAeYTvvNO6u31c: {
      username: "24040301024416u",
      name: "Rendra Angga Saputra",
      school: "SMA Semesta BBS Semarang",
      province: "Jawa Tengah",
    },
    JIDUSERCsLkwJyEwElFaCLPnzck: {
      username: "24040511000705u",
      name: "Annabel Kayla Talitha",
      school: "SMAK Petra 4 Sidoarjo",
      province: "Jawa Timur",
    },
    JIDUSERaLixSyBJcXL2bZ0vQ63j: {
      username: "24040502050617u",
      name: "Faisal Rehan Saputra",
      school: "MAN 2 Kota Malang",
      province: "Jawa Timur",
    },
    JIDUSERL1vbnmuAiluTpLvWcNWF: {
      username: "24040502050618u",
      name: "Hisyam Prasetyo",
      school: "MAN 2 Kota Malang",
      province: "Jawa Timur",
    },
    JIDUSERcK1NGeHuodijIvew8OzL: {
      username: "24040502000818u",
      name: "Rozan Laudzai",
      school: "SMAN 3 Malang",
      province: "Jawa Timur",
    },
    JIDUSERSUJfLQyk1jmL79yGoSbq: {
      username: "24040501008104u",
      name: "Abel Dean Eberhard",
      school: "SMAK Petra 3 Surabaya",
      province: "Jawa Timur",
    },
    JIDUSER5YCLHYjpx7JVwLYaaalu: {
      username: "24040501011415u",
      name: "Evan William Winarto",
      school: "SMAK Petra 2 Surabaya",
      province: "Jawa Timur",
    },
    JIDUSERgJvJTCEGU0L0K9N4698Y: {
      username: "24040501007618u",
      name: "Halim Putra Widjaja",
      school: "SMAK St. Louis 1 Surabaya",
      province: "Jawa Timur",
    },
    JIDUSERrjnNmaH709jTYbDC58Nf: {
      username: "24040501007619u",
      name: "Kenneth Nicholas Gunawan",
      school: "SMAK St. Louis 1 Surabaya",
      province: "Jawa Timur",
    },
    JIDUSERKmisr0jPCQJxNPM5gb7Q: {
      username: "24040501001519u",
      name: "Rayyan Aqsha Raditya",
      school: "SMAN 5 Surabaya",
      province: "Jawa Timur",
    },
    JIDUSERjson47Uf0Vmhnavwf07S: {
      username: "24040501005520u",
      name: "Syauqi Faza",
      school: "SMAN 16 Surabaya",
      province: "Jawa Timur",
    },
    JIDUSERWj5H9dyPBU381RU6GBuS: {
      username: "24041301006503p",
      name: "Warren Xing",
      school: "SMP Bina Mulia Pontianak",
      province: "Kalimantan Barat",
    },
    JIDUSERICCerEwfbbGPSsWqXR2q: {
      username: "24041511002618u",
      name: "Muhammad Zulfan Atqya",
      school: "MAN Insan Cendekia Tanah Laut",
      province: "Kalimantan Selatan",
    },
    JIDUSERoGiJeaIAEBvpjo8HD7gM: {
      username: "24041403001516u",
      name: "Nicholas Han",
      school: "SMAK Taruna Jaya Sampit",
      province: "Kalimantan Tengah",
    },
    JIDUSERBxwDrr2Kd05kZrhsKJt9: {
      username: "24041601003316u",
      name: "Muhammad Dhafin Al Khairy",
      school: "MAN 2 Samarinda",
      province: "Kalimantan Timur",
    },
    JIDUSERIh4ppsOStnP4NiBcEhqF: {
      username: "24041601001013u",
      name: "Ravee Lucky Rizky Kangiden",
      school: "SMAN 10 Samarinda",
      province: "Kalimantan Timur",
    },
    JIDUSERNZSC4kf03DVUciySjtJn: {
      username: "24043402000320u",
      name: "Ucok Kamal",
      school: "SMAN 3 Tarakan",
      province: "Kalimantan Utara",
    },
    JIDUSERzX3lbFwiI9BLRFI4DSCL: {
      username: "24042801000520u",
      name: "Zakary Nareswara Tulus Sinudewangga Hatmadipura",
      school: "SMA Santo Yosef Pangkal Pinang",
      province: "Kep. Bangka Belitung",
    },
    JIDUSER09XLoeZGMzNmJUKlTJuO: {
      username: "24043101000117u",
      name: "Dylan Hans",
      school: "SMAN 1 Tanjungpinang",
      province: "Kep. Riau",
    },
    JIDUSERqXyGFWguBWuMx8UCOM6W: {
      username: "24041201004719u",
      name: "Rana Azka Hanania",
      school: "SMA Al-Kautsar Bandar Lampung",
      province: "Lampung",
    },
    JIDUSERkIymwGjkXbHlI2spPdIM: {
      username: "24041202000118u",
      name: "Fatih Naufal Habibillah",
      school: "SMAN 1 Metro",
      province: "Lampung",
    },
    JIDUSERQXcrmOjC2tRY8WEQ1hgX: {
      username: "24042101000118u",
      name: "Joyandro Gerard Diasz",
      school: "SMAN 1 Ambon",
      province: "Maluku",
    },
    JIDUSERTBZGXMS6rJ6h98VRvASS: {
      username: "24042702000114u",
      name: "M. Zulfan Halil",
      school: "SMAN 1 Tidore Kepulauan",
      province: "Maluku Utara",
    },
    JIDUSERh4zcXEh0VaiYZyB6bcwK: {
      username: "24042301001717u",
      name: "Bryan Valentino Poernomo",
      school: "SMAK Kusuma Cakranegara",
      province: "Nusa Tenggara Barat",
    },
    JIDUSERHwhDBS5KyYqCAvhbHB9c: {
      username: "24042414000819u",
      name: "Refinus Nathanael Sunur",
      school: "SMAK Frater Don Bosco Lewoleba",
      province: "Nusa Tenggara Timur",
    },
    JIDUSERM9U8DXp2aDujpn8QHDu9: {
      username: "24042501000818u",
      name: "Gregorius Abner",
      school: "SMAN 4 Jayapura",
      province: "Papua",
    },
    JIDUSERgwDvxPKrFi0DfydMLfnw: {
      username: "24043301000516u",
      name: "Arindi Ulfa Salsabila",
      school: "SMAN 2 Manokwari",
      province: "Papua Barat",
    },
    JIDUSERJqmiDjvxTtTZCjfGjHBn: {
      username: "24043801000917u",
      name: "Arjun Pratama",
      school: "SMA Averos Sorong",
      province: "Papua Barat Daya",
    },
    JIDUSERjMWQOuJ1Oqhl2hanotdQ: {
      username: "24043701000117u",
      name: "Jerico K Lumempow",
      school: "SMAN 1 Wamena",
      province: "Papua Pegunungan",
    },
    JIDUSERR2SDvZynKG3M63CccyDs: {
      username: "24043501000318u",
      name: "Muhammad Dhiya Elfatah Matdoan",
      school: "SMAN 3 Merauke",
      province: "Papua Selatan",
    },
    JIDUSERkzZgLT9jTk38et5j9wzX: {
      username: "24043601000317u",
      name: "Nurul Azisa",
      school: "SMAN 3 Nabire",
      province: "Papua Tengah",
    },
    JIDUSERnW1zh8soVV498iLwHzOo: {
      username: "24040910000417u",
      name: "Nicholas",
      school: "SMAN 1 Tualang",
      province: "Riau",
    },
    JIDUSERsMnbf7EXS8lBtk0ZgCsn: {
      username: "24040902000616u",
      name: "Atanasius Brilliant Siringo Ringo",
      school: "SMAN Binaan Khusus Kota Dumai",
      province: "Riau",
    },
    JIDUSERsVBsn68ZaVuCfqVHlC8t: {
      username: "24040901010117u",
      name: "Aldiraj Damar Windani",
      school: "MAN 1 Pekanbaru",
      province: "Riau",
    },
    JIDUSEReY3NMpfVCTYQ6GLRx2xO: {
      username: "24040901010217u",
      name: "Dimas Bayu Nugroho",
      school: "MAN 2 Pekanbaru",
      province: "Riau",
    },
    JIDUSERzt0GD3iIlMEMeNPQkL8B: {
      username: "24040901004717u",
      name: "Franklin Filbert Irwan",
      school: "SMA Darma Yudha Pekanbaru",
      province: "Riau",
    },
    JIDUSER1tqv8ZGWpSeDdjlsth5P: {
      username: "24040901004720u",
      name: "Nathanael Nicolas Chang",
      school: "SMA Darma Yudha Pekanbaru",
      province: "Riau",
    },
    JIDUSER6K14eP7OkSHKr9X5mmI0: {
      username: "24043203000120u",
      name: "Reyhan Fahreza",
      school: "SMAN 1 Polewali",
      province: "Sulawesi Barat",
    },
    JIDUSER3KFaDTcGQ8wjyq10GdrR: {
      username: "24041906100420u",
      name: "Yahdilil Haq Sarifuddin",
      school: "MAN Insan Cendekia Gowa",
      province: "Sulawesi Selatan",
    },
    JIDUSERUpG0nDhCI0TVZrVxAMQP: {
      username: "24041901009116u",
      name: "Adriel Jansen Siahaya",
      school: "SMAK Rajawali Makassar",
      province: "Sulawesi Selatan",
    },
    JIDUSEREaOH9WRUcazVCg5xYEiH: {
      username: "24041901030202p",
      name: "Jose William Theruna",
      school: "SMP Bambini Makassar",
      province: "Sulawesi Selatan",
    },
    JIDUSERMa1DfWl8rLCE1xpH2Ldq: {
      username: "24041801003520u",
      name: "Wahyu Pratama Anugrah",
      school: "SMA Islam Al-Azhar Mandiri Palu",
      province: "Sulawesi Tengah",
    },
    JIDUSERApbtqsZIFONNxOuymaQt: {
      username: "24042001000816u",
      name: "Juan Erico Andriano",
      school: "SMAN 4 Kendari",
      province: "Sulawesi Tenggara",
    },
    JIDUSERfalA06ABwj5MCwKK5M9B: {
      username: "24041703000715u",
      name: "Feryan Krishany Jonandri",
      school: "SMA Lokon St. Nikolaus Tomohon",
      province: "Sulawesi Utara",
    },
    JIDUSERUoeaMOZnSAOmVvtEJO2y: {
      username: "24040812020418u",
      name: "Muhammad Siddiq Parchan",
      school: "MAN Insan Cendekia Padang Pariaman",
      province: "Sumatera Barat",
    },
    JIDUSERq4VSaZf0265EVyPXQctg: {
      username: "24041101013116u",
      name: "Christivan Komah",
      school: "SMA Ignatius Global School Palembang",
      province: "Sumatera Selatan",
    },
    JIDUSERidDfTJ9xx51WtT2u30Hg: {
      username: "24041101013117u",
      name: "Ezra Azka Einnos",
      school: "SMA Ignatius Global School Palembang",
      province: "Sumatera Selatan",
    },
    JIDUSERBRmWN0ELKm7L0WYWQZFO: {
      username: "24041101005517u",
      name: "Leroy Ben Orvill",
      school: "SMA Kusuma Bangsa Palembang",
      province: "Sumatera Selatan",
    },
    JIDUSERD4t40kg8US3qja55yCyQ: {
      username: "24040720001918u",
      name: "Jeremy Radase Dollyputra Nainggolan",
      school: "SMA Unggul Del",
      province: "Sumatera Utara",
    },
    JIDUSERTKaFLq41RVqQ2wKZIPbY: {
      username: "24040701007517u",
      name: "Ethan Keenan Chua",
      school: "SMA Sutomo 1 Medan",
      province: "Sumatera Utara",
    },
    JIDUSERYol8scQTp3iOBbVn05MO: {
      username: "24040701007518u",
      name: "Nicholas Alvin Willie",
      school: "SMA Sutomo 1 Medan",
      province: "Sumatera Utara",
    },
    JIDUSERlNlJEgj4yxss6cJ5IrYL: {
      username: "24040702002116u",
      name: "Justin Sepvian",
      school: "SMAK Kalam Kudus Pematangsiantar",
      province: "Sumatera Utara",
    },
  },
};
